set WFDB=C:\Users\Public\Work\QRS-detector\ECG_DB\NSTDB;
: file: NST-wqrs-valid.bat	ecgeval		13 August 2026
:
: Evaluate test annotator wqrs on the NST DB

: This file was automatically generated by ecgeval.  Do not edit it
: unless you know what you are doing!

: Record 118
bxb -r 118 -a atr wqrs -l bxb.out sd.out
rxr -r 118 -a atr wqrs -l vruns.out 
mxm -r 118 -a atr wqrs -L hr0.out -m 0

: Record 118e24
bxb -r 118e24 -a atr wqrs -l bxb.out sd.out
rxr -r 118e24 -a atr wqrs -l vruns.out 
mxm -r 118e24 -a atr wqrs -L hr0.out -m 0

: Record 118e18
bxb -r 118e18 -a atr wqrs -l bxb.out sd.out
rxr -r 118e18 -a atr wqrs -l vruns.out 
mxm -r 118e18 -a atr wqrs -L hr0.out -m 0

: Record 118e12
bxb -r 118e12 -a atr wqrs -l bxb.out sd.out
rxr -r 118e12 -a atr wqrs -l vruns.out 
mxm -r 118e12 -a atr wqrs -L hr0.out -m 0

: Record 118e06
bxb -r 118e06 -a atr wqrs -l bxb.out sd.out
rxr -r 118e06 -a atr wqrs -l vruns.out 
mxm -r 118e06 -a atr wqrs -L hr0.out -m 0

: Record 118e00
bxb -r 118e00 -a atr wqrs -l bxb.out sd.out
rxr -r 118e00 -a atr wqrs -l vruns.out 
mxm -r 118e00 -a atr wqrs -L hr0.out -m 0

: Record 118e_6
bxb -r 118e_6 -a atr wqrs -l bxb.out sd.out
rxr -r 118e_6 -a atr wqrs -l vruns.out 
mxm -r 118e_6 -a atr wqrs -L hr0.out -m 0

: Record 119
bxb -r 119 -a atr wqrs -l bxb.out sd.out
rxr -r 119 -a atr wqrs -l vruns.out 
mxm -r 119 -a atr wqrs -L hr0.out -m 0

: Record 119e24
bxb -r 119e24 -a atr wqrs -l bxb.out sd.out
rxr -r 119e24 -a atr wqrs -l vruns.out 
mxm -r 119e24 -a atr wqrs -L hr0.out -m 0

: Record 119e18
bxb -r 119e18 -a atr wqrs -l bxb.out sd.out
rxr -r 119e18 -a atr wqrs -l vruns.out 
mxm -r 119e18 -a atr wqrs -L hr0.out -m 0

: Record 119e12
bxb -r 119e12 -a atr wqrs -l bxb.out sd.out
rxr -r 119e12 -a atr wqrs -l vruns.out 
mxm -r 119e12 -a atr wqrs -L hr0.out -m 0

: Record 119e06
bxb -r 119e06 -a atr wqrs -l bxb.out sd.out
rxr -r 119e06 -a atr wqrs -l vruns.out 
mxm -r 119e06 -a atr wqrs -L hr0.out -m 0

: Record 119e00
bxb -r 119e00 -a atr wqrs -l bxb.out sd.out
rxr -r 119e00 -a atr wqrs -l vruns.out 
mxm -r 119e00 -a atr wqrs -L hr0.out -m 0

: Record 119e_6
bxb -r 119e_6 -a atr wqrs -l bxb.out sd.out
rxr -r 119e_6 -a atr wqrs -l vruns.out 
mxm -r 119e_6 -a atr wqrs -L hr0.out -m 0

: Generate summary report
echo Beat detection and classification performance >>NST-report-wqrs.txt
echo >>NST-report-wqrs.txt
sumstats bxb.out >>NST-report-wqrs.txt
echo >>NST-report-wqrs.txt
echo Analysis shutdowns >>NST-report-wqrs.txt
echo >>NST-report-wqrs.txt
sumstats sd.out >>NST-report-wqrs.txt
echo >>NST-report-wqrs.txt
echo Ventricular ectopic run detection performance >>NST-report-wqrs.txt
echo >>NST-report-wqrs.txt
sumstats vruns.out >>NST-report-wqrs.txt
echo >>NST-report-wqrs.txt
echo Heart rate measurement number 0 performance >>NST-report-wqrs.txt
echo >>NST-report-wqrs.txt
sumstats hr0.out >>NST-report-wqrs.txt
echo >>NST-report-wqrs.txt
echo The evaluation is complete.  Print text file NST-report-wqrs.txt
echo to get the results.
